### ISSUE TITLE
How to use keypath?

### ISSUE THREAD

**Issue by mstang** [nathanmarz/specter#33] opened 2015-10-30 03:34 UTC
I have a question concerning keypath, I see how you created a param-compiled, but how do I pass it a list of params? The example shows (param-compiled :a :b :c), so how would I pass it a list (:a :b :c)? I have a "path" (i.e."/Shops/shop0001/cust0001") that I can split into (Shops shop0001 cust0001), but how do I pass it to select/transform? I have tried map and apply but everything gives me errors back.

**Comment by mstang** [comment] 2015-10-30 13:30
I have tried: 
Hard-coded example of using keypath:

    (println (s/select [(s/keypath "Shops")(s/keypath "shop0001")(s/keypath "cust0001")] results))

I could write a function with an arity of  0, 1, 2, 3
I can create a reusable function:


    (def param-compiled (s/comp-paths s/keypath s/keypath s/keypath s/keypath s/keypath))
    (defn get-param-compiled [arg results]
      (let [args (split-path arg)
            arg0 (nth args 0)
            arg1 (nth args 1)
            arg2 (nth args 2)
            arg3 (nth args 3)
            arg4 (nth args 4)]
        (s/select [(param-compiled arg0 arg1 arg2 arg3 arg4)] results)
        ))

However, it seems like I have to hard-code everything for a query.  Is there a better way?
I guess I could wrap this in a macro, however I am getting to the edge of my Clojure skills here.

**Comment by nathanmarz** [comment] 2015-10-30 16:13
I'm not clear on what you were trying originally that wasn't working. Can you provide a simple reproducible test case?

**Comment by hooptie45** [comment] 2015-10-31 05:04
@mstang - I think you want something like this:
```clojure
(defn path-selector [path]
  (s/comp-paths (map s/keypath (.split path "/"))))
```
#### Given:
```clojure
(def db
  {"Shops" {"shop-1" {"cust-1" "PATH: Shops/shop-1/cust-1"
                      "cust-2" "PATH: Shops/shop-1/cust-2"}
            "shop-2" {"cust-1" "PATH: Shops/shop-2/cust-1"
                      "cust-2" "PATH: Shops/shop-2/cust-2"}}})

```

#### Usage:
##### Simple `select`
```clojure
(select-one (path-selector "Shops/shop-2/cust-2") db)
;; =>
;; "PATH: Shops/shop-2/cust-2"
```

##### Basic `setval`
```clojure
(clojure.pprint/pprint
 (s/setval [(path-selector "Shops/shop-2/cust-2")]
           "CHANGED PATH: Shops/shop-2/cust-2" db))
;; =>
;; {"Shops"
;;  {"shop-1"
;;   {"cust-1" "PATH: Shops/shop-1/cust-1",
;;    "cust-2" "PATH: Shops/shop-1/cust-2"},
;;   "shop-2"
;;   {"cust-1" "PATH: Shops/shop-2/cust-1",
;;    "cust-2" "CHANGED PATH: Shops/shop-2/cust-2"}}}
```

##### basic `transform`
```clojure 
(clojure.pprint/pprint
 (s/transform [(path-selector "Shops/shop-2/cust-2")
                        (s/putval "CHANGED ")]
              str
              db))
;; =>
;; {"Shops"
;;  {"shop-1"
;;   {"cust-1" "PATH: Shops/shop-1/cust-1",
;;    "cust-2" "PATH: Shops/shop-1/cust-2"},
;;   "shop-2"
;;   {"cust-1" "PATH: Shops/shop-2/cust-1",
;;    "cust-2" "CHANGED PATH: Shops/shop-2/cust-2"}}}
```

##### `compiled-transform` **Note the `s/comp-paths` in place of vector**
```clojure
(clojure.pprint/pprint
 (s/compiled-transform (s/comp-paths (path-selector "Shops/shop-2/cust-2")
                                                 (s/putval "CHANGED "))
              str
              db))
;; =>
;; {"Shops"
;;  {"shop-1"
;;   {"cust-1" "PATH: Shops/shop-1/cust-1",
;;    "cust-2" "PATH: Shops/shop-1/cust-2"},
;;   "shop-2"
;;   {"cust-1" "PATH: Shops/shop-2/cust-1",
;;    "cust-2" "CHANGED PATH: Shops/shop-2/cust-2"}}}
```

##### `multi-path` `transform`
```clojure
(clojure.pprint/pprint
 (s/transform [(path-selector "Shops/shop-2")
               (multi-path (path-selector "cust-1")
                           (path-selector "cust-2"))
               (putval "CHANGED ")]
              str
              db))
;; =>
;; {"Shops"
;;  {"shop-1"
;;   {"cust-1" "PATH: Shops/shop-1/cust-1",
;;    "cust-2" "PATH: Shops/shop-1/cust-2"},
;;   "shop-2"
;;   {"cust-1" "CHANGED PATH: Shops/shop-2/cust-1",
;;    "cust-2" "CHANGED PATH: Shops/shop-2/cust-2"}}}

```

**Comment by mstang** [comment] 2015-10-31 14:34
So, what I am trying to do is to create a function that I can pass a list of strings and a map to do a select or a transform. 

The list of strings starts out as a path:

    "/Shops/shop0001/cust0001/veh0001/job0001"

I have helper functions to "split" the path into a list or vector of strings:

    (println "str/split:" (str/split "/Shops/shop0001/cust0001/veh0001/job0001" #"/"))
    (println "map:" (map s/keypath (split-path "/Shops/shop0001/cust0001/veh0001/job0001")))

The result of these is:

    split-path: (shop0001 cust0001 veh0001 job0001)
    str/split: [ Shops shop0001 cust0001 veh0001 job0001]

The map looks like:

    results: {Shops {shop0001 {cust0001 {:path /Shops/shop0001/cust0001, :last-name Stang, :first-name Mark, veh0001 {:path /Shops/shop0001/cust0001/veh0001, job0002 {:path /Shops/shop0001/cust0001/veh0001/job0002, :job-id job0002}, :make Ford, job0001 {:path /Shops/shop0001/cust0001/veh0001/job0001, :job-id job0001}}, veh0002 {:path /Shops/shop0001/cust0001/veh0002, :make VW}}}}} 

So, what I want to be able to do is to do something like:

    (println "select using map:" (s/select [(map s/keypath (split-path "/Shops/shop0001/cust0001/veh0001/job0001"))] results))

The solutions I have found are:

    (println "five segments:" (s/select [(s/keypath "Shops")(s/keypath "shop0001")(s/keypath "cust0001")(s/keypath "veh0001")(s/keypath "job0001")] results))

    five segments: [{:path /Shops/shop0001/cust0001/veh0001/job0001, :job-id job0001}]

and 

    (def param-compiled (s/comp-paths s/keypath s/keypath s/keypath s/keypath s/keypath))
    (defn get-param-compiled [arg results]
      (let [args (split-path arg)
            arg0 (nth args 0)
            arg1 (nth args 1)
            arg2 (nth args 2)
            arg3 (nth args 3)
            arg4 (nth args 4)]
        (s/select [(param-compiled arg0 arg1 arg2 arg3 arg4)] results)
        ))
    (println "param-compiled:" (get-param-compiled "/Shops/shop0001/cust0001/veh0001/job0001" results))
    
    param-compiled: [{:path /Shops/shop0001/cust0001/veh0001/job0001, :job-id job0001}]

This combination def param-compiled and the function get-param-compiled example shows how I created a function that takes five path segments and does a select.  I could continue that paradigm and create a def/function combination for each possible combination of arguments(i.e. 1 arg, two args, three, args, four args, five args, ...).  Even going as far as to pass in the function (i.e. s/select or s/transform). 

So, I guess my question is how to pass in a list of strings/parameters to a select or a transform that represents the path to be acted on?
It seems that keypath isn't composable.  So, is there a better way?

The actual code for this is in https://github.com/mstang/pathdatabase.git, starting at line 108 if that helps.

**Comment by mstang** [comment] 2015-10-31 16:28
Wow, I will give that a shot.

Thanks!

**Comment by mstang** [comment] 2015-10-31 16:45
Are you running this in a Clojure environment?

I tried the "Simple select" inside of a ClojureScript environment and I get:

Uncaught Error: Protocol implementation cannot be found for object.
        Extending Specter protocols should not be done inline in a deftype
definition
        because that prevents Specter from finding the protocol
implementations for
        optimized performance. Instead, you should extend the protocols via
an
        explicit extend-protocol call.
(#com.rpl.specter.impl.CompiledPath{:transform-fns
#com.rpl.specter.impl.TransformFunctions{:executors
#object[com.rpl.specter.impl.ExecutorFunctions], :selector #object[Function
"function
(params21552,params_idx21553,vals__21554__auto__,structure,next_fn__21555__auto__){
var next_fn = (function (structure__21556__auto__){
return next_fn__21555__auto__.call(null,params21552,(params_idx21553 +
1),vals__21554__auto__,structure__21556__auto__);
});
var key = (params21552[(params_idx21553 + (0))]);
return next_fn.call(null,cljs.core.get.call(null,structure,key));
}"], :transformer #object[Function "function
(params21552,params_idx21553,vals__21554__auto__,structure,next_fn__21555__auto__){
var next_fn = (function (structure__21556__auto__){
return next_fn__21555__auto__.call(null,params21552,(params_idx21553 +
1),vals__21554__auto__,structure__21556__auto__);
});
var key = (params21552[(params_idx21553 + (0))]);
return
cljs.core.assoc.call(null,structure,key,next_fn.call(null,cljs.core.get.call(null,structure,key)));
}"]}, :params #js ["Shops"], :params-idx 0}
#com.rpl.specter.impl.CompiledPath{:transform-fns
#com.rpl.specter.impl.TransformFunctions{:executors
#object[com.rpl.specter.impl.ExecutorFunctions], :selector #object[Function
"function
(params21552,params_idx21553,vals__21554__auto__,structure,next_fn__21555__auto__){
var next_fn = (function (structure__21556__auto__){
return next_fn__21555__auto__.call(null,params21552,(params_idx21553 +
1),vals__21554__auto__,structure__21556__auto__);
});
var key = (params21552[(params_idx21553 + (0))]);
return next_fn.call(null,cljs.core.get.call(null,structure,key));
}"], :transformer #object[Function "function
(params21552,params_idx21553,vals__21554__auto__,structure,next_fn__21555__auto__){
var next_fn = (function (structure__21556__auto__){
return next_fn__21555__auto__.call(null,params21552,(params_idx21553 +
1),vals__21554__auto__,structure__21556__auto__);
});
var key = (params21552[(params_idx21553 + (0))]);
return
cljs.core.assoc.call(null,structure,key,next_fn.call(null,cljs.core.get.call(null,structure,key)));
}"]}, :params #js ["shop0001"], :params-idx 0}
#com.rpl.specter.impl.CompiledPath{:transform-fns
#com.rpl.specter.impl.TransformFunctions{:executors
#object[com.rpl.specter.impl.ExecutorFunctions], :selector #object[Function
"function
(params21552,params_idx21553,vals__21554__auto__,structure,next_fn__21555__auto__){
var next_fn = (function (structure__21556__auto__){
return next_fn__21555__auto__.call(null,params21552,(params_idx21553 +
1),vals__21554__auto__,structure__21556__auto__);
});
var key = (params21552[(params_idx21553 + (0))]);
return next_fn.call(null,cljs.core.get.call(null,structure,key));
}"], :transformer #object[Function "function
(params21552,params_idx21553,vals__21554__auto__,structure,next_fn__21555__auto__){
var next_fn = (function (structure__21556__auto__){
return next_fn__21555__auto__.call(null,params21552,(params_idx21553 +
1),vals__21554__auto__,structure__21556__auto__);
});
var key = (params21552[(params_idx21553 + (0))]);
return
cljs.core.assoc.call(null,structure,key,next_fn.call(null,cljs.core.get.call(null,structure,key)));
}"]}, :params #js ["cust0001"], :params-idx 0})

Thanks!

Mark

**Comment by hooptie45** [comment] 2015-11-01 00:29
@mstang Yes, I was using clojure in my examples, (I was assuming the functionality would be the same in both). I pulled down your repo and got similar errors. It appears that this will only work in cljs if you use `keyword` keys. This modified function seams to work, provided your data structure uses `keyword` keys.

```clojure
(defn path-selector [path]
  (let [segments (str/split path #"/")
        ;; On paths that begin with a slash, we will get an empty
        ;; string for the first segment; therefore we must remove it
        segments (filter (partial (complement empty?)) segments)
        segments (map keyword segments)]
    (into [] segments)))
````

**Comment by mstang** [comment] 2015-11-02 00:28
Thanks for experimenting with that.  I don't want to change everything to use keywords unless that is my only choice.  I am waiting to see what Nathan says before I make my decision.

**Comment by nathanmarz** [comment] 2015-11-03 15:56
The code from @hooptie45 didn't work in CLJS because of a small bug in Specter where comp-paths wouldn't work on lazy seqs in CLJS. That bug will be fixed in 0.8.1. For now, with 0.8.0, you can make the code work in both environments by changing `path-selector` to either of these:

```clojure
(defn path-selector [path]
  (apply s/comp-paths (map s/keypath (.split path "/"))))

(defn path-selector [path]
  (s/comp-paths (mapv s/keypath (.split path "/"))))
```

**Comment by mstang** [comment] 2015-11-03 16:51
Great!  I will give it a try in my environment!

Thanks!

**Comment by hooptie45** [comment] 2015-11-03 18:14
Thanks! Very informative.

**Closed** 2015-11-04 07:46 UTC

**Comment by mstang** [comment] 2015-11-05 04:09
That works great!

Thanks!

**Comment by mstang** [comment] 2015-11-06 00:41
@hooptie45 Thanks for all your examples, they all work now with Nathan's work-around.
