### ISSUE TITLE
setval throwing an exception when being used in a threading macro

### ISSUE THREAD

**Issue by imrekoszo** [nathanmarz/specter#157] opened 2016-11-11 14:17 UTC
From the slack log in #specter on clojurians:
[1:37 PM]  
hi all

[1:38]  
I would be grateful if someone could give me advice on building paths dynamically using a navigator in 0.13.1

[1:38]  
my navigator is like this

[1:38]  
 ```clojure
(sp/defnav
  EID
  [eid]
  (select* [{:keys [eid]} structure next-fn] (eid-nav-select* eid structure next-fn))
  (transform* [{:keys [eid]} structure next-fn] (eid-nav-transform* eid structure next-fn)))
```

[1:39]  
and this is how I try to build a path from a list of keys

[1:39]  
 ```clojure
(defn- specter-path [ks]
  (map #(if (u/uuid? %)
          (EID %)
          %)
       ks))
```

[1:41]  
and getting a `Cannot statically combine sequential when not in nav pos` error when invoking specter-path

imre	[1:49 PM]  
well actually the error comes when I try to use the path in a call to `setval`

imre	[2:02 PM]  
well, I managed to fix it however I don't exactly know why it failed.

[2:02]  
so the calling code looked like this:

[2:02]  
 ```clojure
(-> (concat [:_entity] ks)
          specter-path
          (sp/setval value stored-entity))
```
(edited)

[2:03 PM]  
but when I defined this function
```clojure
(defn- setval [apath aval structure]
  (sp/setval apath aval structure))
```
and replaced `sp/setval` with `setval` inside the threading macro, it worked

nathanmarz	[2:12 PM]  
@imre that looks like a bug

[2:12]  
can you open an issue on github for it?

[2:12]  
you can workaround it by doing `(let [p (specter-path ...)] (setval p ...))`

**Comment by nathanmarz** [comment] 2016-12-06 13:20
I looked into this and am unable to reproduce this.

**Comment by nathanmarz** [comment] 2016-12-21 18:52
Closing due to inability to reproduce.

**Closed by nathanmarz** 2016-12-21 18:52 UTC
Labels: bug

**Comment by mkorvas** [comment] 2017-04-11 20:20
This seems to be a good minimal example:
```clojure
(require '[com.rpl.specter :refer [transform]])

(let [specter-key [:state]]
  (transform (concat [] specter-key) identity {}))
```

**Comment by mkorvas** [comment] 2017-04-11 20:39
Attached a trace of a slightly "more minimal" example.
[select-trace.txt](https://github.com/nathanmarz/specter/files/914617/select-trace.txt)

**Comment by nathanmarz** [comment] 2017-04-11 21:25
Looks like this is already fixed on master. Try 1.0.1-SNAPSHOT

**Comment by mkorvas** [comment] 2017-04-12 20:49
Indeed, this is not an issue with 1.0.1-SNAPSHOT. Good news!
