### ISSUE TITLE
Protocol implementation cannot be found for object / no namespace: com.rpl.specter

### ISSUE THREAD

**Issue by LusciousPear** [nathanmarz/specter#68] opened 2016-03-02 18:18 UTC
Hi,

I'm seeing these exceptions trying to run this from a dependencies-included jar built in maven. The code works fine in the REPL. 

Just including specter in the ns causes the errors. 

Any ideas? :)

```(3fa92a8448e8098d): Exception: java.lang.IllegalArgumentException: Protocol implementation cannot be found for object. Extending Specter protocols should not be done inline in a deftype definition because that prevents Specter from finding the protocol implementations for optimized performance. Instead, you should extend the protocols via an explicit extend-protocol call. com.rpl.specter.impl.AllStructurePath@6f84f479, compiling:(specter.clj:154:10) clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558) clojure.lang.Compiler$DefExpr.eval(Compiler.java:417) clojure.lang.Compiler.eval(Compiler.java:6708) clojure.lang.Compiler.load(Compiler.java:7130) clojure.lang.RT.loadResourceScript(RT.java:370) clojure.lang.RT.loadResourceScript(RT.java:361) clojure.lang.RT.load(RT.java:440) clojure.lang.RT.load(RT.java:411) clojure.core$load$fn__1476.invoke(core.clj:5641) clojure.core$load.doInvoke(core.clj:5640) clojure.lang.RestFn.invoke(RestFn.java:408) clojure.core$load_one.invoke(core.clj:5446) clojure.core$load_lib$fn__1425.invoke(core.clj:5486) clojure.core$load_lib.doInvoke(core.clj:5485) clojure.lang.RestFn.applyTo(RestFn.java:142) clojure.core$apply.invoke(core.clj:626) clojure.core$load_libs.doInvoke(core.clj:5524) clojure.lang.RestFn.applyTo(RestFn.java:137) clojure.core$apply.invoke(core.clj:626) clojure.core$require.doInvoke(core.clj:5607) clojure.lang.RestFn.invoke(RestFn.java:436) extractorion$eval3880$loading__1352__auto____3881.invoke(extractorion.clj:1) extractorion$eval3880.invoke(extractorion.clj:1) clojure.lang.Compiler.eval(Compiler.java:6703) clojure.lang.Compiler.eval(Compiler.java:6692) clojure.lang.Compiler.load(Compiler.java:7130) clojure.lang.RT.loadResourceScript(RT.java:370) clojure.lang.RT.loadResourceScript(RT.java:361) clojure.lang.RT.load(RT.java:440) clojure.lang.RT.load(RT.java:411) clojure.core$load$fn__1476.invoke(core.clj:5641) clojure.core$load.doInvoke(core.clj:5640) clojure.lang.RestFn.invoke(RestFn.java:408) clojure.core$load_one.invoke(core.clj:5446) clojure.core$load_lib$fn__1425.invoke(core.clj:5486) clojure.core$load_lib.doInvoke(core.clj:5485) clojure.lang.RestFn.applyTo(RestFn.java:142) clojure.core$apply.invoke(core.clj:626) clojure.core$load_libs.doInvoke(core.clj:5524) clojure.lang.RestFn.applyTo(RestFn.java:137) clojure.core$apply.invoke(core.clj:626) clojure.core$require.doInvoke(core.clj:5607) clojure.lang.RestFn.invoke(RestFn.java:408) clojure.lang.Var.invoke(Var.java:379) com.acacia.pipeline.orionbigquery.InvokeOrionBigQueryTransformer.transform(InvokeOrionBigQueryTransformer.java:29) com.acacia.pipeline.orionbigquery.InvokeOrionBigQueryTransformer.transform(InvokeOrionBigQueryTransformer.java:53) com.acacia.sdk.AbstractTransformComposer.processElement(AbstractTransformComposer.java:44) Caused By: java.lang.IllegalArgumentException: Protocol implementation cannot be found for object. Extending Specter protocols should not be done inline in a deftype definition because that prevents Specter from finding the protocol implementations for optimized performance. Instead, you should extend the protocols via an explicit extend-protocol call. com.rpl.specter.impl.AllStructurePath@6f84f479 sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) java.lang.reflect.Constructor.newInstance(Constructor.java:422) clojure.lang.Reflector.invokeConstructor(Reflector.java:180) com.rpl.specter.impl$eval4986$fn__4987.invoke(impl.clj:257) com.rpl.specter.impl$eval4969$fn__4970$G__4960__4975.invoke(impl.clj:220) ...```

and

```(13be20ed0e33e02): Exception: java.lang.Exception: No namespace: com.rpl.specter, compiling:(extractorion.clj:1:1) clojure.lang.Compiler.load(Compiler.java:7142) clojure.lang.RT.loadResourceScript(RT.java:370) clojure.lang.RT.loadResourceScript(RT.java:361) clojure.lang.RT.load(RT.java:440) clojure.lang.RT.load(RT.java:411) clojure.core$load$fn__1476.invoke(core.clj:5641) clojure.core$load.doInvoke(core.clj:5640) clojure.lang.RestFn.invoke(RestFn.java:408) clojure.core$load_one.invoke(core.clj:5446) clojure.core$load_lib$fn__1425.invoke(core.clj:5486) clojure.core$load_lib.doInvoke(core.clj:5485) clojure.lang.RestFn.applyTo(RestFn.java:142) clojure.core$apply.invoke(core.clj:626) clojure.core$load_libs.doInvoke(core.clj:5524) clojure.lang.RestFn.applyTo(RestFn.java:137) clojure.core$apply.invoke(core.clj:626) clojure.core$require.doInvoke(core.clj:5607) clojure.lang.RestFn.invoke(RestFn.java:408) clojure.lang.Var.invoke(Var.java:379) com.acacia.pipeline.orionbigquery.InvokeOrionBigQueryTransformer.transform(InvokeOrionBigQueryTransformer.java:29) com.acacia.pipeline.orionbigquery.InvokeOrionBigQueryTransformer.transform(InvokeOrionBigQueryTransformer.java:53) com.acacia.sdk.AbstractTransformComposer.processElement(AbstractTransformComposer.java:44) Caused By: java.lang.Exception: No namespace: com.rpl.specter clojure.core$refer.doInvoke(core.clj:3902) clojure.lang.RestFn.applyTo(RestFn.java:139) ...```

**Comment by nathanmarz** [comment] 2016-03-04 13:53
Are you doing aot compilation? What's the fastest way I can reproduce this?

**Comment by LusciousPear** [comment] 2016-03-07 13:40
Yeah, AOT. I'll put up a repo you can repro from.

On Fri, Mar 4, 2016 at 1:53 PM, Nathan Marz <notifications@github.com>
wrote:

> Are you doing aot compilation? What's the fastest way I can reproduce this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nathanmarz/specter/issues/68#issuecomment-192292131>.
>



-- 
Bradford Stephens
Freelance CTO & Startup Exec
22acacia.com
(530) 763-DATA

**Comment by nathanmarz** [comment] 2016-06-28 01:22
I did some tests with aot compiled projects in uberjars and fixed #132 to get it working. I don't know what's causing this specific issue, but I was unable to reproduce it. Closing, but feel free to re-open if you provide a repo that can reproduce this with 0.12.0-SNAPSHOT.

**Closed by nathanmarz** 2016-06-28 01:22 UTC
